# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json


class Ui_form_settings(object):
    def setupUi(self, form_settings):
        form_settings.setObjectName("form_settings")
        form_settings.resize(380, 430)
        
        self.txt_sender = QtWidgets.QLineEdit(form_settings)
        self.txt_sender.setGeometry(QtCore.QRect(170, 20, 201, 31))
        self.txt_sender.setObjectName("txt_sender")
        
        self.txt_receiver = QtWidgets.QLineEdit(form_settings)
        self.txt_receiver.setGeometry(QtCore.QRect(170, 60, 201, 31))
        self.txt_receiver.setObjectName("txt_receiver")

        self.txt_sender_password = QtWidgets.QLineEdit(form_settings)
        self.txt_sender_password.setGeometry(QtCore.QRect(170, 100, 201, 31))
        self.txt_sender_password.setObjectName("txt_sender_pasword")

        self.txt_smtp_server = QtWidgets.QLineEdit(form_settings)
        self.txt_smtp_server.setGeometry(QtCore.QRect(170, 140, 201, 31))
        self.txt_smtp_server.setObjectName("txt_smtp_server")

        self.txt_smtp_port = QtWidgets.QLineEdit(form_settings)
        self.txt_smtp_port.setGeometry(QtCore.QRect(170, 180, 201, 31))
        self.txt_smtp_port.setObjectName("txt_smtp_port")
        
        self.label = QtWidgets.QLabel(form_settings)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(form_settings)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.label_5 = QtWidgets.QLabel(form_settings)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 160, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.label_3 = QtWidgets.QLabel(form_settings)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(form_settings)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        
        self.btn_save_settings = QtWidgets.QPushButton(form_settings)
        self.btn_save_settings.setGeometry(QtCore.QRect(280, 390, 90, 30))
        self.btn_save_settings.clicked.connect(self.btn_save_settings_click)
        self.btn_save_settings.setObjectName("btn_save_settings")

        self.retranslateUi(form_settings)
        QtCore.QMetaObject.connectSlotsByName(form_settings)

    def retranslateUi(self, form_settings):
        _translate = QtCore.QCoreApplication.translate
        form_settings.setWindowTitle(_translate("form_settings", "Ayarlar"))
        self.label.setText(_translate("form_settings", "Gönderen e-posta"))
        self.label_2.setText(_translate("form_settings", "Alıcı e-posta"))
        self.label_3.setText(_translate("form_settings", "SMTP Server"))
        self.label_4.setText(_translate("form_settings", "SMTP Server Port"))
        self.label_5.setText(_translate("form_settings", "Gönderen şifresi"))
        self.btn_save_settings.setText(_translate("form_settings", "Kaydet"))


    def btn_save_settings_click(self):
        sender = self.txt_sender.text()
        receiver = self.txt_receiver.text()
        smtp_server = self.txt_smtp_server.text()
        smtp_server_port = self.txt_smtp_port.text()
        sender_password = self.txt_sender_password.text()
        Ui_form_settings.save_data(sender, receiver, sender_password, smtp_server, smtp_server_port)

    def save_data(sender, receiver, sender_password, smtp_server, smtp_server_port):
        # settings.txt dosyasını sıfırla (boşalt)
        with open('settings.txt', 'w') as file:
            file.write('[]')
        
        # Yeni verileri ekle
        data = [{'sender': sender, 'receiver': receiver, 'sender_password': sender_password, 'smtp_server': smtp_server, 'smtp_server_port': smtp_server_port}]
        with open('settings.txt', 'w') as file:
            json.dump(data, file, indent=4)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_settings = QtWidgets.QDialog()
    ui = Ui_form_settings()
    ui.setupUi(form_settings)
    form_settings.show()
    sys.exit(app.exec_())
